### ISSUE TITLE
cannot install `pta` using `pip`

### ISSUE THREAD

**Issue by eladnoor** [marco-corrao/iCH360_paper#5]
Not sure if this is a platform issue, but I couldn't install the `pta` package using the `pip` directly.
Did you solve this in some other way? Maybe good to explain this in the Readme.

**Comment by marco-corrao** [comment]
Have you specified not to install the sampler, by running
```
PTA_NO_SAMPLERS=1 pip install pta             # Linux, OSX
set "PTA_NO_SAMPLERS=1" && pip install pta    # Windows
```
?
(from https://probabilistic-thermodynamic-analysis.readthedocs.io/en/latest/getting_started.html)

I think installing the sampler dependencies is trickier, especially on Windows, but not needed for this project. If that works for you, I'll add this to the readme.

**Comment by eladnoor** [comment]
Yes, this worked for me

**Comment by marco-corrao** [comment]
A note on this was added on the readme file in the Analysis folder.
